export const LOAD_COLLECTIONS_REQUESTED = "LOAD_COLLECTIONS";
export const LOAD_COLLECTIONS_SUCCEEDED = "LOAD_COLLECTIONS_SUCCEEDED";
export const LOAD_COLLECTIONS_FAILED = "LOAD_COLLECTIONS_FAILED";
