export const LOAD_COLLECTIONS_REQUESTED = "LOAD_COLLECTIONS_REQUESTED";
export const LOAD_COLLECTIONS_SUCCEEDED = "LOAD_COLLECTIONS_SUCCEEDED";
export const LOAD_COLLECTIONS_FAILED = "LOAD_COLLECTIONS_FAILED";

export const CREATE_COLLECTION_REQUESTED = "CREATE_COLLECTION_REQUESTED";
export const CREATE_COLLECTION_SUCCEEDED = "CREATE_COLLECTION_SUCCEEDED";
export const CREATE_COLLECTION_FAILED = "CREATE_COLLECTION_FAILED";
